djangoAPItienda/api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    path('v1/product/', views.Product_APIView.as_view(), name='Products'), 
    path('v1/product/<int:pk>/', views.Product_APIView_Detail.as_view(), name='Detail'),
    
    path('v1/user/', views.Usuario_APIView.as_view(), name='Usuarios'), 
    path('v1/user/<int:pk>/', views.Usuario_APIView_Detail.as_view(), name='Detail'),
    
    path('v1/comment/', views.Comment_APIView.as_view(), name='Comments'), 
    path('v1/comment/<int:pk>/', views.Comment_APIView_Detail.as_view(), name='Detail'),
]

djangoAPItienda/djangoAPItienda/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('tiendamain.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
]

djangoAPItienda/tiendamain/urls.py
from django.urls import path
from . import views

app_name = 'tiendamain'
urlpatterns = [
    path("", views.IndexView.as_view(), name="Index"), 
    path("editar_prod/<int:pk>/", views.editar_product, name="editar_prod"), 
    path("ingresar_prod/", views.ingresar_product, name="ingresar_prod"), 
]

djangoAPItienda/api/models.py
from django.db import models

# Create your models here.
class Usuario(models.Model):
    email = models.EmailField(max_length=40)
    nickname = models.CharField(max_length=100)
    realname = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    
    def __str__(self):
        return self.nickname
class Product(models.Model):
    name = models.CharField(max_length=100)
    img_url = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    mod_date = models.DateTimeField(auto_now_add=True)
    serial_num = models.IntegerField()
    price = models.DecimalField(max_digits=20, decimal_places=2)
    # rating = models.DecimalField(max_digits=3, decimal_places=1)
    
    def __str__(self):
        return self.name
class Comment(models.Model):
    prod_rating = models.DecimalField(max_digits=3, decimal_places=1)
    prod_num = models.IntegerField()
    pub_date = models.DateTimeField(auto_now_add=True)
    user_mail = models.EmailField()
    text_comment = models.TextField()
    
    def __str__(self):
        return self.text_comment

djangoAPItienda/tiendamain/models.py
from django.db import models

# Create your models here.

djangoAPItienda/api/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializers import ProductSerializer, CommentSerializer, UsuarioSerializer
from .models import Product, Comment, Usuario
from rest_framework import status
from django.http import Http404


# Create your views here.
class Product_APIView(APIView):
    def get(self, request, format=None, *args, **kwargs):
        product = Product.objects.all()
        serializer = ProductSerializer(product, many=True)
        
        return Response(serializer.data)
    
    def post(self, request, format=None, *args, **kwargs):
        serializer = ProductSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
class Product_APIView_Detail(APIView):
    def get_object(self, pk):
        try:
            return Product.objects.get(pk=pk)
        except Product.DoesNotExist:
            raise Http404
        
    def get(self, request, pk, format=None):
        product = self.get_object(pk)
        serializer = ProductSerializer(product)
        return Response(serializer.data)
    
    def put(self, request, pk, format=None):
        product = self.get_object(pk)
        serializer = ProductSerializer(product, request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def delete(self, request, pk, format=None):
        product = self.get_object(pk)
        product.delete()
        return Response(status = status.HTTP_204_NO_CONTENT)
    
class Usuario_APIView(APIView):
    def get(self, request, format=None, *args, **kwargs):
        usuarios = Usuario.objects.all()
        serializer = UsuarioSerializer(usuarios, many=True)
        
        return Response(serializer.data)
    
    def post(self, request, pk, format=None):
        serializer = UsuarioSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
class Usuario_APIView_Detail(APIView):
    def get_object(self, pk):
        try:
            return Usuario.objects.get(pk=pk)
        except Usuario.DoesNotExist:
            raise Http404
        
    def get(self, request, pk, format=None):
        usuario = self.get_object(pk)
        serializer = UsuarioSerializer(usuario)
        return Response(serializer.data)
    
    def put(self, request, pk, format=None):
        usuario = self.get_object(pk)
        serializer = UsuarioSerializer(usuario, request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def delete(self, request, pk, format=None):
        usuario = self.get_object(pk)
        usuario.delete()
        return Response(status = status.HTTP_204_NO_CONTENT)
    
class Comment_APIView(APIView):
    def get(self, request, format=None, *args, **kwargs):
        comments = Comment.objects.all()
        serializer = CommentSerializer(comments, many=True)
        
        return Response(serializer.data)
    
    def post(self, request, pk, format=None):
        serializer = CommentSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
class Comment_APIView_Detail(APIView):
    def get_object(self, pk):
        try:
            return Comment.objects.get(pk=pk)
        except Comment.DoesNotExist:
            raise Http404
        
    def get(self, request, pk, format=None):
        comment = self.get_object(pk)
        serializer = CommentSerializer(comment)
        return Response(serializer.data)
    
    def put(self, request, pk, format=None):
        comment = self.get_object(pk)
        serializer = CommentSerializer(comment, request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def delete(self, request, pk, format=None):
        comment = self.get_object(pk)
        comment.delete()
        return Response(status = status.HTTP_204_NO_CONTENT)
    

djangoAPItienda/tiendamain/views.py
from django.shortcuts import render
from django.views import generic
import requests
from api.models import Usuario, Comment, Product

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'tiendaMain/index.html'
    context_object_name = "latest_product_list"
    
    def get_queryset(self):
        products = requests.get("http://127.0.0.1:8000/api/v1/product/")
        return products.json()
        
def editar_product(request, pk):
    template_name = 'tiendaMain/editar.html'
    producto = requests.get("http://127.0.0.1:8000/api/v1/product/{}".format(pk)).json()
    context = {
        'producto': producto
    }
    return render(request, template_name, context)

def ingresar_product(request):
    template_name = 'tiendaMain/ingresar.html'
    return render(request, template_name)

djangoAPItienda/tiendamain/templates/tiendaMain/editar.html
<h1>Hola</h1>

{% block head %}
    <head>
        {% load static %}
    </head>
{% endblock head %}

{% block content %}
    <div class="formulario">
        <form action="" id="form">
            <!-- <label for="id">Id:</label><br> -->
            <input type="text" name="id" id="input_id" value="{{ producto.id }}" disabled hidden="true">
            <label for="name">Nombre:</label><br>
            <input type="text" name="name" id="input_name" value="{{ producto.name }}"><br>
            
            <label for="img_url">Url Imagen:</label><br>
            <input type="text" name="img_url" id="input_iurl" value="{{ producto.img_url }}"><br>
            
            <label for="description">Descripcion:</label><br>
            <input type="text" name="description" id="input_desc" value="{{ producto.description }}"><br>
            
            <label for="serial_num">Serial num:</label><br>
            <input type="number" name="serial_num" id="input_num" value="{{ producto.serial_num }}"><br>
            
            <label for="price">Precio:</label><br>
            <input type="number" name="price" id="input_price" value="{{ producto.price }}"><br>
            <input type="button" name="Boton_enviar" id="send_btn" value="Modificar">
        </form>
    </div>
{% endblock content %}

{% block footer %}
    <footer>
        {{ producto|json_script:"hello-data" }}
        <script src="{% static 'static_jquery/js/jquery.js' %}"></script>
        <script src="{% static 'js/editar.js' %}"></script>
    </footer>
{% endblock footer %}   

djangoAPItienda/tiendamain/templates/tiendaMain/index.html
<h1>Hola</h1>

{% block head %}
    <head>
        {% load static %}
    </head>
{% endblock head %}

{% block content %}
    <div class="content">
        <a class="postear" href="{% url 'tiendamain:ingresar_prod' %}">Postear</a>
        <div>
            <table id="tabla-productos">
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Descripcion</th>
                    <th>Serial num</th>
                    <th>Precio</th>
                    <th colspan="2">Opciones</th>
                </tr>
            </table>
        </div>
        <input type="button" id="call-product" value="boton">
    </div>
{% endblock content %}

{% block footer %}
    <footer>
        <script src="{% static 'static_jquery/js/jquery.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </footer>
{% endblock footer %}   

djangoAPItienda/tiendamain/templates/tiendaMain/ingresar.html
<h1>Hola</h1>

{% block head %}
    <head>
        {% load static %}
    </head>
{% endblock head %}

{% block content %}
    <div class="formulario">
        <form action="" id="form">
            <label for="name">Nombre:</label><br>
            <input type="text" name="name" id="input_name" ><br>
            
            <label for="img_url">Url Imagen:</label><br>
            <input type="text" name="img_url" id="input_iurl" ><br>
            
            <label for="description">Descripcion:</label><br>
            <input type="text" name="description" id="input_desc" ><br>
            
            <label for="serial_num">Serial num:</label><br>
            <input type="number" name="serial_num" id="input_num" ><br>
            
            <label for="price">Precio:</label><br>
            <input type="number" name="price" id="input_price" ><br>
            <input type="button" name="Boton_enviar" id="send_btn" value="Registrar">
        </form>
    </div>
{% endblock content %}

{% block footer %}
    <footer>
        <script src="{% static 'static_jquery/js/jquery.js' %}"></script>
        <script src="{% static 'js/ingresar.js' %}"></script>
    </footer>
{% endblock footer %}   